# Dataset

In [1]:
import pandas as pd
dataset = pd.read_csv('dataset.csv')
dataset

Nama Peserta BIPA Asal Negara  Mendengarkan  Merespon Kaidah  \
0              Yu Hao Ming       China           440              365   
1            Chong Haobing       China           625              395   
2             Ye Fang Ting       China           470              530   
3         Jessie Panazzalo   Australia           395              440   
4            Jumpei Fukata      Jepang           470              485   
5                   Majeed  Arab Saudi           320              395   
6   Dhenver Quiliza Reyesn    Filipina           470              485   
7       Pham Thi Minh Ngol     Vietnam           440              500   
8             Jamil Rizwan  Afganistan           320              395   
9     Brian Kiprop Ngetich       Kenya           500              512   
10        Mc Donald Baluti      Malawi           488              470   
11             Dao Ming Se       China           605              590   
12                 Brayden   Australia           455              425   
13                   Tiran       Kenya           395              380   
14               Yuki Fira      Jepang           515              455   

    Membaca  Menulis  Berbicara   Kesimpulan  
0       485        1          3  Tidak Lulus  
1       380        3          2        Lulus  
2       440        2          2        Lulus  
3       470        2          3  Tidak Lulus  
4       515        3          3        Lulus  
5       410        3          1  Tidak Lulus  
6       515        2          3        Lulus  
7       536        3          2        Lulus  
8       360        1          2  Tidak Lulus  
9       575        3          3        Lulus  
10      515        3          2        Lulus  
11      620        3          3        Lulus  
12      515        3          3        Lulus  
13      320        1          2  Tidak Lulus  
14      485        3          2        Lulus

# Data CSV --> Array

In [2]:
import numpy as np

dataset.to_numpy()

array([['Yu Hao Ming', 'China', 440, 365, 485, 1, 3, 'Tidak Lulus'],
       ['Chong Haobing', 'China', 625, 395, 380, 3, 2, 'Lulus'],
       ['Ye Fang Ting', 'China', 470, 530, 440, 2, 2, 'Lulus'],
       ['Jessie Panazzalo', 'Australia', 395, 440, 470, 2, 3,
        'Tidak Lulus'],
       ['Jumpei Fukata', 'Jepang', 470, 485, 515, 3, 3, 'Lulus'],
       ['Majeed', 'Arab Saudi', 320, 395, 410, 3, 1, 'Tidak Lulus'],
       ['Dhenver Quiliza Reyesn', 'Filipina', 470, 485, 515, 2, 3,
        'Lulus'],
       ['Pham Thi Minh Ngol', 'Vietnam', 440, 500, 536, 3, 2, 'Lulus'],
       ['Jamil Rizwan', 'Afganistan', 320, 395, 360, 1, 2, 'Tidak Lulus'],
       ['Brian Kiprop Ngetich', 'Kenya', 500, 512, 575, 3, 3, 'Lulus'],
       ['Mc Donald Baluti', 'Malawi', 488, 470, 515, 3, 2, 'Lulus'],
       ['Dao Ming Se', 'China', 605, 590, 620, 3, 3, 'Lulus'],
       ['Brayden', 'Australia', 455, 425, 515, 3, 3, 'Lulus'],
       ['Tiran', 'Kenya', 395, 380, 320, 1, 2, 'Tidak Lulus'],
       ['Yuki Fira'

# Input Data

Keterangan :

x1 = Mendengarkan (400)

x2 = Merespon Kaidah (450)

x3 = Membaca (304)

x4 = Menulis (4)

x5 = Berbicara (4)

K = (3)

In [3]:
x1 = int(input("Nilai Mendengarkan :"))
x2 = int(input("Nilai Merespon Kaidah :"))
x3 = int(input("Nilai Membaca :"))
x4 = int(input("Nilai Menulis :"))
x5 = int(input("Nilai Berbicara :"))
KReturn = int(input("K : "))

X_new = np.array([x1,x2,x3,x4,x5]).reshape(1,-1)
X_new

Nilai Mendengarkan :400
Nilai Merespon Kaidah :450
Nilai Membaca :304
Nilai Menulis :4
Nilai Berbicara :4
K : 3


array([[400, 450, 304,   4,   4]])

# Klasifikasi dengan KNN

In [4]:
X_train = np.array(dataset[['Mendengarkan','Merespon Kaidah','Membaca','Menulis','Berbicara']])
y_train = np.array(dataset['Kesimpulan'])

print(f'X_train:\n{X_train}\n')
print(f'y_train: {y_train}')

X_train:
[[440 365 485   1   3]
 [625 395 380   3   2]
 [470 530 440   2   2]
 [395 440 470   2   3]
 [470 485 515   3   3]
 [320 395 410   3   1]
 [470 485 515   2   3]
 [440 500 536   3   2]
 [320 395 360   1   2]
 [500 512 575   3   3]
 [488 470 515   3   2]
 [605 590 620   3   3]
 [455 425 515   3   3]
 [395 380 320   1   2]
 [515 455 485   3   2]]

y_train: ['Tidak Lulus' 'Lulus' 'Lulus' 'Tidak Lulus' 'Lulus' 'Tidak Lulus' 'Lulus'
 'Lulus' 'Tidak Lulus' 'Lulus' 'Lulus' 'Lulus' 'Lulus' 'Tidak Lulus'
 'Lulus']


# Training KNN

In [5]:
from sklearn.neighbors import KNeighborsClassifier

K = KReturn
model = KNeighborsClassifier(n_neighbors=K)
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

# Kalkulasi Euclidean Distance

In [6]:
from scipy.spatial.distance import euclidean

data_jarak = [euclidean(X_new,d) for d in X_train]
dataset['Jarak'] = data_jarak
dataset.sort_values(['Jarak'])

Nama Peserta BIPA Asal Negara  Mendengarkan  Merespon Kaidah  \
13                   Tiran       Kenya           395              380   
8             Jamil Rizwan  Afganistan           320              395   
5                   Majeed  Arab Saudi           320              395   
3         Jessie Panazzalo   Australia           395              440   
2             Ye Fang Ting       China           470              530   
0              Yu Hao Ming       China           440              365   
14               Yuki Fira      Jepang           515              455   
12                 Brayden   Australia           455              425   
4            Jumpei Fukata      Jepang           470              485   
6   Dhenver Quiliza Reyesn    Filipina           470              485   
10        Mc Donald Baluti      Malawi           488              470   
7       Pham Thi Minh Ngol     Vietnam           440              500   
1            Chong Haobing       China           625              395   
9     Brian Kiprop Ngetich       Kenya           500              512   
11             Dao Ming Se       China           605              590   

    Membaca  Menulis  Berbicara   Kesimpulan       Jarak  
13      320        1          2  Tidak Lulus   72.069411  
8       360        1          2  Tidak Lulus  112.133849  
5       410        3          1  Tidak Lulus  143.774128  
3       470        2          3  Tidak Lulus  166.391106  
2       440        2          2        Lulus  172.638350  
0       485        1          3  Tidak Lulus  203.950975  
14      485        3          2        Lulus  214.513403  
12      515        3          3        Lulus  219.483485  
4       515        3          3        Lulus  225.051105  
6       515        2          3        Lulus  225.057770  
10      515        3          2        Lulus  229.499455  
7       536        3          2        Lulus  240.684441  
1       380        3          2        Lulus  243.784741  
9       575        3          3        Lulus  295.443734  
11      620        3          3        Lulus  401.849474

In [7]:
y_new = model.predict(X_new)
y_new

array(['Tidak Lulus'], dtype=object)